### ISSUE TITLE
Availabilty to fix wallpaper or lockscreen 

### ISSUE THREAD

**Issue by Bernhelm** [rodakorn/randwall#1]
As a user I would like to lock my wallpaper or my lockscreen wallpaper and only randomize the other one. Lock both of them would be nonsense and yet posible.

I'll try this weekend to send you a pull request :)

**Comment by rodakorn** [comment]
Hey!

Thanks for the idea! I've modified the extension to let you choose what you want to change (desktop only, lockscreen only, both desktop and lockscreen using different images or both using the same image. I'm not really sure if that is what you asked for, but if you had another thing in mind feel free to send me a pull request ;).

**Comment by Bernhelm** [comment]
Thanks!, that's exactly what I was asking for!
