### ISSUE TITLE
Hide icon ?

### ISSUE THREAD

**Issue by redianthus** [rodakorn/randwall#10]
Hi, I was wondering if it could be possible to add a "hide icon" option ? As, once it's configured, if you don't want to change manually your wallpaper every 30 seconds, the icon is not very useful and also, because I like to have a topbar as "clean" as possible. Thanks.

**Comment by rodakorn** [comment]
Done

**Comment by redianthus** [comment]
Thx ! :)

**Comment by redianthus** [comment]
@rodakorn I updated from gnome extensions website, works thine, thx again ! I just saw that the translation has not been done, I searched, but didn't find how to suggest a translation, so I give it to you here...

The french translation of "Hide icon" is "Masquer l'icône".
