### ISSUE TITLE
TypeError: this.MyTimer is undefined

### ISSUE THREAD

**Issue by vboufleur** [rodakorn/randwall#15]
Hi, I'm having the error on the title on my fedora 23 with GNOME 3.18.2.

Here's the relevant log from 'journalctl /usr/bin/gnome-shell': http://pastie.org/private/nhvhtc890kdhehnydvocg

**Comment by slashome** [comment]
Same issue here, I'unable to use this extension :/

**Comment by rodakorn** [comment]
Hi
I'm using 3.16 on my computer and I have no problems with this last version. I will try to check on a 3.18.

**Comment by slashome** [comment]
I'm on Gnome 3.20 on ArchLinux, sorry to not mentioned it before :)

**Comment by rodakorn** [comment]
Hi
I think I've found something involving this error when the screen is locked... specifically when the screen goes blank. 

I've uploaded a new version. Please, let me know if this fixes your problem.

**Comment by vboufleur** [comment]
Well, it was a sporadic error, has been some time since it happened. I installed the new version and will report if this error happens again. Thanks for the awesome extension!!
