### ISSUE TITLE
Option to don't switch wallpapers per time 

### ISSUE THREAD

**Issue by alex285** [rodakorn/randwall#17]
Can be an option that that won't change wallpapers? Just an On/Off switch next to Interval?
I'm only using this extension so I can set my wallpapers folders, and switch backgrounds manually, because G-C-C doesn't let you.

**Comment by rodakorn** [comment]
Mmmm, ok, It's not that difficult. I will make it, but these days I'm a little busy at work so It will take me some time to do this.

**Comment by Omar007** [comment]
A pause button as in the BackSlide extension would be nice indeed.

**Comment by rodakorn** [comment]
Hi!

Now it's posible to set a 0 minute interval so wallpapers only switch manually.
