### ISSUE TITLE
Support subfolders

### ISSUE THREAD

**Issue by TravellingGuy** [rodakorn/randwall#2]
Hi.

The plugin doesn't seem to support subfolders, it only finds pictures in the folder selected and doesn't recurse into subdirectories. I have a folder where all my pictures are sorted by year, it would be great if you could add support for scanning all subdirectories.

**Comment by rodakorn** [comment]
Done!

I couldn't test it properly (only the basic functionality) so, if you see any error, please tell me and I will try to correct it ;)
I only updated the code here in the github version of the extension. Tomorrow I will test the extension and if it works properly I will update the extensions.gnome.org version.

**Comment by rodakorn** [comment]
I've tested the changes and it works well. It's already uploaded to extensions.gnome.org waiting to be approved.
