### ISSUE TITLE
[Solved] Gnome 3.38 compatibility

### ISSUE THREAD

**Issue by knobsam** [rodakorn/randwall#45]
Hi,

can you update the extension to be compatible with Gnome version 3.38, please?
It is no longer working with Fedora 33 or other distributions which are using newer Gnome releases.

Best regards,

Samuel

**Comment by knobsam** [comment]
@rodakorn Are you still maintaining this project or is it abandoned?

**Comment by mrEDitor** [comment]
I'm not the author, but I still use the extension on Archlinux (Gnome Shell 3.38.1) and it works fine enough.
But I remember [the bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2284) in Gnome Shell which breaks the auto-fetching feature of extension. There is a workaround [found on Archlinux bug-tracker](https://bugs.archlinux.org/task/62860) but it seems to introduce some kind of security issues (I'm not sure about this) and should not be used, I suppose.
Are you able to switch wallpapers by the "New wallpaper" button in the menu?
Also, do you have any errors or warnings in `journalctl /usr/bin/gnome-shell` regarding the extension?

**Comment by kgarner7** [comment]
I guess I'll comment here, #47 should have resolved this issue

**Comment by knobsam** [comment]
Sorry for the late response.
I've tried it, works like a charm.

Thank you very much (this can be closed now).
