### ISSUE TITLE
Selecting a specific image doesn't work

### ISSUE THREAD

**Issue by urandom** [rodakorn/randwall#9]
Hi,

The readme mentions that clicking on an image preview would allow you to select an image. For me, nothing happens when you click either of the images.

**Comment by mrEDitor** [comment]
Hello. What version of shell and extension do you use? Does the "next" button work?

**Comment by cedlemo** [comment]
I have the same issue. For the version, I have this message in my console when I run gnome-tweak-tool:

```
INFO    : e.g.o no updates for Random_Walls@Antares (shell version 3.18.3 extension version 6.0)
```

**Comment by mrEDitor** [comment]
That issue was fixed by me (#6). Seems like @rodakorn didn't update the extension on extensions.gnome.org yet.

**Comment by rodakorn** [comment]
Yep. I've uploaded the new version a few days ago to extensions.gnome.org with this bug fixed but is still pending approval.

**Comment by urandom** [comment]
After updating from github, that feature looks like it's working

**Comment by rodakorn** [comment]
I didn't receive any complaints related to this problem so I'm closing the issue.
